version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_AI_SERVER_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules

  # Backend Service
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=myweb
      - DB_USER=myweb_user
      - DB_PASSWORD=0626
      - JWT_SECRET=7467b45843394edb87494a4428275135
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - /app/node_modules
      - ../backend/uploads:/app/uploads

  # AI Server Service
  ai-server:
    build:
      context: ../ai-server
      dockerfile: ../docker/Dockerfile.ai
    ports:
      - "8000:8000"
    environment:
      # Google Translate는 API 키가 불필요합니다
      - DEBUG=True
    volumes:
      - ../ai-server:/app
      - ../data:/app/data

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=0626
      - MYSQL_DATABASE=myweb
      - MYSQL_USER=myweb_user
      - MYSQL_PASSWORD=0626
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - ai-server

volumes:
  mysql_data: 