

services:
  # Frontend Service
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    # ports:
    #   - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost/api
      - REACT_APP_AI_SERVER_URL=http://localhost/ai
      - REACT_APP_KAKAO_REST_API_KEY=${REACT_APP_KAKAO_REST_API_KEY}
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=myweb
      - DB_USER=myweb_user
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost:3000
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - GEMINI_API_KEY=AIzaSyBPReCZhgjhBC5THxIqpbhrIjpiSRQ__Hw
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - /app/node_modules
      - ../backend/uploads:/app/uploads

  # AI Server Service
  ai-server:
    build:
      context: ../ai-server
      dockerfile: ../docker/Dockerfile.ai
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ../ai-server:/app
      - ../data:/app/data

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=myweb
      - MYSQL_USER=myweb_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Nginx Reverse Proxy (API 프록시만)
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - ai-server

volumes:
  mysql_data:
