services:
  ai-server:
    build:
      context: ../ai-server
      dockerfile: ../docker/Dockerfile.ai
    container_name: docker_ai-server
    env_file:
      - ../docker/env.prod
    networks:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: docker_backend
    env_file:
      - ../docker/env.prod
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend.prod
    container_name: docker_frontend
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    container_name: docker_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=myweb
    volumes:
      - mysql_data:/var/lib/mysql
    # 운영에서는 외부 포트 노출을 피하는 것을 권장합니다. 필요 시만 열어주세요.
    # ports:
    #   - "3307:3306"
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  mysql_data:
